// <auto-generated />
using DataClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLibrary.Migrations
{
    [DbContext(typeof(GuildDatabase))]
    [Migration("20220215202625_newdatabases")]
    partial class newdatabases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataModels.GuildRanks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GuildRankName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("GuildRanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuildRankName = "Guild Master"
                        },
                        new
                        {
                            Id = 2,
                            GuildRankName = "Officer"
                        },
                        new
                        {
                            Id = 3,
                            GuildRankName = "Member"
                        },
                        new
                        {
                            Id = 4,
                            GuildRankName = "Trial"
                        });
                });

            modelBuilder.Entity("DataModels.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AltRoleID")
                        .HasColumnType("int");

                    b.Property<int>("GuildRankID")
                        .HasColumnType("int");

                    b.Property<int>("PlayerClassID")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DataModels.Roles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Tank"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Healer"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Melee DPS"
                        },
                        new
                        {
                            RoleID = 4,
                            RoleName = "Ranged DPS"
                        });
                });

            modelBuilder.Entity("DataModels.Specs", b =>
                {
                    b.Property<int>("SpecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecID"), 1L, 1);

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SpecID");

                    b.ToTable("Specs");

                    b.HasData(
                        new
                        {
                            SpecID = 1,
                            ClassID = 1,
                            RoleID = 1,
                            SpecName = "Blood"
                        },
                        new
                        {
                            SpecID = 2,
                            ClassID = 1,
                            RoleID = 3,
                            SpecName = "Frost"
                        },
                        new
                        {
                            SpecID = 3,
                            ClassID = 1,
                            RoleID = 3,
                            SpecName = "Blood"
                        },
                        new
                        {
                            SpecID = 4,
                            ClassID = 2,
                            RoleID = 1,
                            SpecName = "Vengeance"
                        },
                        new
                        {
                            SpecID = 5,
                            ClassID = 2,
                            RoleID = 3,
                            SpecName = "Havoc"
                        },
                        new
                        {
                            SpecID = 6,
                            ClassID = 3,
                            RoleID = 1,
                            SpecName = "Guardian"
                        },
                        new
                        {
                            SpecID = 7,
                            ClassID = 3,
                            RoleID = 2,
                            SpecName = "Restoration"
                        },
                        new
                        {
                            SpecID = 8,
                            ClassID = 3,
                            RoleID = 3,
                            SpecName = "Feral"
                        },
                        new
                        {
                            SpecID = 9,
                            ClassID = 3,
                            RoleID = 4,
                            SpecName = "Balance"
                        },
                        new
                        {
                            SpecID = 10,
                            ClassID = 4,
                            RoleID = 3,
                            SpecName = "Survival"
                        },
                        new
                        {
                            SpecID = 11,
                            ClassID = 4,
                            RoleID = 4,
                            SpecName = "Beast Mastery"
                        },
                        new
                        {
                            SpecID = 12,
                            ClassID = 4,
                            RoleID = 4,
                            SpecName = "Marksmanship"
                        },
                        new
                        {
                            SpecID = 13,
                            ClassID = 5,
                            RoleID = 4,
                            SpecName = "Fire"
                        },
                        new
                        {
                            SpecID = 14,
                            ClassID = 5,
                            RoleID = 4,
                            SpecName = "Frost"
                        },
                        new
                        {
                            SpecID = 15,
                            ClassID = 5,
                            RoleID = 4,
                            SpecName = "Arcane"
                        },
                        new
                        {
                            SpecID = 16,
                            ClassID = 6,
                            RoleID = 1,
                            SpecName = "Brewmaster"
                        },
                        new
                        {
                            SpecID = 17,
                            ClassID = 6,
                            RoleID = 2,
                            SpecName = "Mistweaver"
                        },
                        new
                        {
                            SpecID = 18,
                            ClassID = 6,
                            RoleID = 3,
                            SpecName = "Windwalker"
                        },
                        new
                        {
                            SpecID = 19,
                            ClassID = 7,
                            RoleID = 1,
                            SpecName = "Protection"
                        },
                        new
                        {
                            SpecID = 20,
                            ClassID = 7,
                            RoleID = 2,
                            SpecName = "Holy"
                        },
                        new
                        {
                            SpecID = 21,
                            ClassID = 7,
                            RoleID = 3,
                            SpecName = "Retribution"
                        },
                        new
                        {
                            SpecID = 22,
                            ClassID = 8,
                            RoleID = 2,
                            SpecName = "Discipline"
                        },
                        new
                        {
                            SpecID = 23,
                            ClassID = 8,
                            RoleID = 2,
                            SpecName = "Holy"
                        },
                        new
                        {
                            SpecID = 24,
                            ClassID = 8,
                            RoleID = 4,
                            SpecName = "Shadow"
                        },
                        new
                        {
                            SpecID = 25,
                            ClassID = 9,
                            RoleID = 3,
                            SpecName = "Outlaw"
                        },
                        new
                        {
                            SpecID = 26,
                            ClassID = 9,
                            RoleID = 3,
                            SpecName = "Subtlety"
                        },
                        new
                        {
                            SpecID = 27,
                            ClassID = 9,
                            RoleID = 3,
                            SpecName = "Assassination"
                        },
                        new
                        {
                            SpecID = 28,
                            ClassID = 10,
                            RoleID = 2,
                            SpecName = "Restoration"
                        },
                        new
                        {
                            SpecID = 29,
                            ClassID = 10,
                            RoleID = 3,
                            SpecName = "Enhancement"
                        },
                        new
                        {
                            SpecID = 30,
                            ClassID = 10,
                            RoleID = 4,
                            SpecName = "Elemental"
                        },
                        new
                        {
                            SpecID = 31,
                            ClassID = 11,
                            RoleID = 4,
                            SpecName = "Destruction"
                        },
                        new
                        {
                            SpecID = 32,
                            ClassID = 11,
                            RoleID = 4,
                            SpecName = "Demonology"
                        },
                        new
                        {
                            SpecID = 33,
                            ClassID = 11,
                            RoleID = 4,
                            SpecName = "Affliction"
                        },
                        new
                        {
                            SpecID = 34,
                            ClassID = 12,
                            RoleID = 1,
                            SpecName = "Protection"
                        },
                        new
                        {
                            SpecID = 35,
                            ClassID = 12,
                            RoleID = 3,
                            SpecName = "Fury"
                        },
                        new
                        {
                            SpecID = 36,
                            ClassID = 12,
                            RoleID = 3,
                            SpecName = "Arms"
                        });
                });

            modelBuilder.Entity("DataModels.Teams", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"), 1L, 1);

                    b.Property<int>("MaxTeamSize")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DataModels.WowClasses", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ClassID");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            ClassName = "Death Knight"
                        },
                        new
                        {
                            ClassID = 2,
                            ClassName = "Demon Hunter"
                        },
                        new
                        {
                            ClassID = 3,
                            ClassName = "Druid"
                        },
                        new
                        {
                            ClassID = 4,
                            ClassName = "Hunter"
                        },
                        new
                        {
                            ClassID = 5,
                            ClassName = "Mage"
                        },
                        new
                        {
                            ClassID = 6,
                            ClassName = "Monk"
                        },
                        new
                        {
                            ClassID = 7,
                            ClassName = "Paladin"
                        },
                        new
                        {
                            ClassID = 8,
                            ClassName = "Priest"
                        },
                        new
                        {
                            ClassID = 9,
                            ClassName = "Rogue"
                        },
                        new
                        {
                            ClassID = 10,
                            ClassName = "Shaman"
                        },
                        new
                        {
                            ClassID = 11,
                            ClassName = "Warlock"
                        },
                        new
                        {
                            ClassID = 112,
                            ClassName = "Warrior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
